### ISSUE TITLE
Customer should be able to turn off auto renewal

### ISSUE THREAD

**Issue by svscherpenseel** [neostrada/whmcs#2]
Customer should be able to turn off auto renewal. When auto renewal is turned off, the domain should be deleted at Neostrada. When auto renewal is turned on again, the deletion should be undone.

**Comment by flexxdesign** [comment]
Hi Stefan,

Ik mis deze functie nog, komt dit er nog aan?

**Comment by svscherpenseel** [comment]
Deze functie is al een tijd geleden geïmplementeerd. Ik zie dat de push dit issue niet heeft gesloten, dus bij deze. Bedankt voor het melden!
